### ISSUE TITLE
Code Style Guide or Prettier Config

### ISSUE THREAD

**Issue by slimeonmyhead** [NeurProjects/neur-app#14]
**Is your feature request related to a problem? Please describe.**
The current codebase is a little inconsistent (usage of semicolons for example). I had to disable all formatting when editing to avoid tons of changes

**Describe the solution you'd like**
Add a prettier config or some code style/formatter guide to allow for consistent changes to be done by outside contributors

**Describe alternatives you've considered**
Disabling formatters which results in inconsistent code style

**Comment by 0xSpotly** [comment]
Hello. It should be settled now.
