### ISSUE TITLE
No direct access to some data 

### ISSUE THREAD

**Issue by tommycrpt** [NeurProjects/neur-app#26]
**Is your feature request related to a problem? Please describe.**

Neur says that it doesn't have the total number of unique wallet holders, etc. 

**Describe the solution you'd like**
This information might be available through:

Solana blockchain explorers
Token tracking services
Project's official analytics

<img width="764" alt="Screenshot 2024-12-26 at 23 16 54" src="https://github.com/user-attachments/assets/a54aa9e5-973b-4adb-9f5a-2a6b45bf7ee9" />

**Comment by KardassVinayKumar** [comment]
I hope this helps 

https://solscan.io/token/3N2ETvNpPNAxhcaXgkhKoY1yDnQfs41Wnxsx5qNJpump#holders

**Comment by 0xSpotly** [comment]
Implemented
