### ISSUE TITLE
Dark Mode Toggle

### ISSUE THREAD

**Issue by akiraloli** [NeurProjects/neur-app#28]
Would like to have a dark mode toggle. 

Right now i have to go into my system settings and turn my whole operating system into dark mode. A nice toggle option would make it much user-friendly and cooler : D

**Comment by 0xSpotly** [comment]
<img width="220" alt="image" src="https://github.com/user-attachments/assets/64bebbc3-4df9-4ee8-abd1-bc3f109b7f40" />

Hi, should be available now. Please check the site.
