### ISSUE TITLE
NOT ABLE TO SELL any token on the app 

### ISSUE THREAD

**Issue by Abbs21111** [NeurProjects/neur-app#29]
Error when selling 
Neur app is unable toi sell my tokens , while i was able to buy tokens ( multiple ) but unable to sell any token 

Now i dont know if this is just related to my account or a general feature 
1- Ask the copilot to bring up my portfolio
2- bring up the token in this case neur/sh token
3- ask it to sell and it keeps repeating the same behaviour ive tried for 50 times now

i Have run the app on 
laptop chrome windows 11
and from my smartphone android both bring the same result 

now i do believe that such a problem is probably limited to my account only , additionally since no private key is given upon signing up i cant move the funds anywhere or access through another wallet

I have signed up using the phantom wallet login method and obviously it created a new wallet address not using the phantom wallet address
![sell error one](https://github.com/user-attachments/assets/305180f2-884d-4fbf-b749-8da69bbbba94)

**Comment by FixResolution** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WB240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by 0xSpotly** [comment]
Working on it

**Comment by 0xSpotly** [comment]
Hello. This problem should be solved. If the problem persists, please reopen

**Comment by Abbs21111** [comment]
Hello, this alone made me buy more thank you for the timely response and fixing the issue
