### ISSUE TITLE
Same listed date and holders amount when showing the tokens asked for

### ISSUE THREAD

**Issue by SoulGeenie** [NeurProjects/neur-app#7]
When the tokens asked for are produced, they all have the same amount of holders and same listed date!

Picture: ![asdada](https://github.com/user-attachments/assets/46768b41-2e8f-4c8a-9a95-99e981ceffb3)

**Comment by 0xSpotly** [comment]
It should have been fixed. Please wait for the deployment to go live and test again.

<img width="688" alt="image" src="https://github.com/user-attachments/assets/9a4dd349-5167-4014-a491-a25a5a1a5b36" />
