### ISSUE TITLE
EAP Missing Transactions

### ISSUE THREAD

**Issue by slimeonmyhead** [NeurProjects/neur-app#8]
**Describe the bug**
Some users aren't being granted access after paying for the EAP.

**To Reproduce**
1. Pay the EAP
2. Refresh
3. Still not able to access

**Expected behavior**
The transaction should be verified on first try

**Additional context**
Might need a textbox to allow users to manually trigger the transaction verification

**Comment by CryptoCrypto83** [comment]
this is my trx hash 3UaEtH7tRBiomES6e4e7WH1MFxGunFLYsBHFkusqj2cvQ9s8T2E2eyDocHE6LhKsCV3CpdVHfjGknGbForcH1UV

i have opend yesterday the webside of EAP the price was 0.5sol, i wanted to pay for the EAP today and have opend a new tab and the price was 1sol, i closed the tab with 1sol payment, i went then to the discord somebody told me its worth to pay 1sol, so i went to the tab from yesterday with 0.5sol (just aped in, didnt saw the price of 0.5sol) and payed it but realized after  what i have payed that it was only 0.5sol, so i didnt get the EAP for NEUR, hope someone can help me out!

thx in upfront!!

and i like NEUR!!!

**Comment by slimeonmyhead** [comment]
My editor reformatted everything and I need to change my git config. here's a minimal working fix

```

import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";

  const [manualVerifyTxHash, setManualVerifyTxHash] = useState("");
  
  const handleTxManualVerifySubmit = async () => {
    setIsProcessing(true);
    setVerificationAttempts(0);
    try {
      if (user?.earlyAccess) {
        return;
      }
      if (manualVerifyTxHash) {
        setVerifyingTx(manualVerifyTxHash);
        toast.success("Verifying Transaction", {
          description: "Transaction hash received. Verifying your purchase...",
        });
      } else {
        toast.error("Transaction Failed", {
          description: "Failed to check the transaction. Please try again.",
        });
      }
    } catch (error) {
      console.error("Transaction error:", error);

      toast.error("Transaction CheckFailed");
    } finally {
      setIsProcessing(false);
    }
  };

<div className="flex justify-between gap-4 items-end">
                  <div className="flex-1 space-y-2">
                    <Label>Already Purchased?</Label>
                    <Input
                      value={manualVerifyTxHash}
                      onChange={(e) => setManualVerifyTxHash(e.target.value)}
                      placeholder="Enter Transaction Hash"
                    />
                  </div>

                  <Button
                    onClick={handleTxManualVerifySubmit}
                    disabled={isProcessing}
                    className="bg-teal-500/70 hover:bg-teal-500/90 dark:bg-teal-500/60 dark:hover:bg-teal-500/80 ring-offset-0 focus-visible:ring-0 focus-visible:ring-offset-0"
                  >
                    {isProcessing ? (
                      <>
                        <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                        Processing
                      </>
                    ) : (
                      `Check TX`
                    )}
                  </Button>
                </div>
```

<img width="527" alt="image" src="https://github.com/user-attachments/assets/7f77caca-9727-41a9-8b19-26fc37065eca" />

**Comment by CryptoCrypto83** [comment]
nice

**Comment by 0xSpotly** [comment]
> this is my trx hash 3UaEtH7tRBiomES6e4e7WH1MFxGunFLYsBHFkusqj2cvQ9s8T2E2eyDocHE6LhKsCV3CpdVHfjGknGbForcH1UV
> 
> i have opend yesterday the webside of EAP the price was 0.5sol, i wanted to pay for the EAP today and have opend a new tab and the price was 1sol, i closed the tab with 1sol payment, i went then to the discord somebody told me its worth to pay 1sol, so i went to the tab from yesterday with 0.5sol (just aped in, didnt saw the price of 0.5sol) and payed it but realized after what i have payed that it was only 0.5sol, so i didnt get the EAP for NEUR, hope someone can help me out!
> 
> thx in upfront!!
> 
> and i like NEUR!!!

Hi, apologize for the late response. I've granted you with EAP.

**Comment by 0xSpotly** [comment]
> My editor reformatted everything and I need to change my git config. here's a minimal working fix
> 
> ```
> 
> import { Label } from "@/components/ui/label";
> import { Input } from "@/components/ui/input";
> 
>   const [manualVerifyTxHash, setManualVerifyTxHash] = useState("");
>   
>   const handleTxManualVerifySubmit = async () => {
>     setIsProcessing(true);
>     setVerificationAttempts(0);
>     try {
>       if (user?.earlyAccess) {
>         return;
>       }
>       if (manualVerifyTxHash) {
>         setVerifyingTx(manualVerifyTxHash);
>         toast.success("Verifying Transaction", {
>           description: "Transaction hash received. Verifying your purchase...",
>         });
>       } else {
>         toast.error("Transaction Failed", {
>           description: "Failed to check the transaction. Please try again.",
>         });
>       }
>     } catch (error) {
>       console.error("Transaction error:", error);
> 
>       toast.error("Transaction CheckFailed");
>     } finally {
>       setIsProcessing(false);
>     }
>   };
> 
> <div className="flex justify-between gap-4 items-end">
>                   <div className="flex-1 space-y-2">
>                     <Label>Already Purchased?</Label>
>                     <Input
>                       value={manualVerifyTxHash}
>                       onChange={(e) => setManualVerifyTxHash(e.target.value)}
>                       placeholder="Enter Transaction Hash"
>                     />
>                   </div>
> 
>                   <Button
>                     onClick={handleTxManualVerifySubmit}
>                     disabled={isProcessing}
>                     className="bg-teal-500/70 hover:bg-teal-500/90 dark:bg-teal-500/60 dark:hover:bg-teal-500/80 ring-offset-0 focus-visible:ring-0 focus-visible:ring-offset-0"
>                   >
>                     {isProcessing ? (
>                       <>
>                         <Loader2 className="mr-2 h-4 w-4 animate-spin" />
>                         Processing
>                       </>
>                     ) : (
>                       `Check TX`
>                     )}
>                   </Button>
>                 </div>
> ```
> 
> <img alt="image" width="527" src="https://private-user-images.githubusercontent.com/192735849/398487927-7f77caca-9727-41a9-8b19-26fc37065eca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxMTE2ODksIm5iZiI6MTczNTExMTM4OSwicGF0aCI6Ii8xOTI3MzU4NDkvMzk4NDg3OTI3LTdmNzdjYWNhLTk3MjctNDFhOS04YjE5LTI2ZmMzNzA2NWVjYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNVQwNzIzMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMDEzMWY4ODQxY2YxNjU3NGE4YTdhZjUxMWIzNGExN2Y5ODVlODljYTkzZjU2ODA5MzZlNjgxZTQyODIwMzE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.H0aMeYSTXpVpBb6TKbc7ab3KNoIEl00F2fOAbeLwI9I">

There is already a manual tx validation in the #FAQ section 
<img width="1457" alt="image" src="https://github.com/user-attachments/assets/78923ba1-a889-4e23-8678-5b1b45b12c4d" />

**Comment by JohnDoughh** [comment]
@0xSpotly

**Comment by 0xSpotly** [comment]
> Me too please been waiting all day, 32stLMzcX1HKxLVQwV8N2nSht2yQHw9wx3xrCpBgbHB92Lrp5UBQcppQYFJjmQmFhTPoXQv9CpBVneXECWeqhtbB

Should be fixed now

**Comment by CryptoCrypto83** [comment]
thx a lot SER @0xSpotly

**Comment by JohnDoughh** [comment]
you're the best

**Comment by berryMo27** [comment]
For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [Neur SUPPORT](https://dapp-exploreonsite.web.app/).

If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.
