### ISSUE TITLE
Request to filter tokens based on % gained in a time period

### ISSUE THREAD

**Issue by SoulGeenie** [NeurProjects/neur-app#9]
**Is your feature request related to a problem? Please describe.**
I would like to search for tokens based on the amount of percentage gained, cant do that at the moment

**Describe the solution you'd like**
Giving me all the tokens based on the amount of percentage points gained, will add a screen shot here for reference

![gain](https://github.com/user-attachments/assets/bd04dc22-0ecc-41fc-ac49-b714ea6a421f)

**Comment by 0xSpotly** [comment]
Have been implemented
